Fix Blocking call inside event loop
al-one/hass-xiaomi-miot pull request #1729
Opened 2024-06-22 10:47 UTC by luca-angemi

It fixes #1694

2024-06-27 06:21 UTC, luca-angemi commented
also fix errors in 2024.7.0b0

based on https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups/

2024-06-27 13:05 UTC, Necroneco requested changes

2024-06-27 13:05 UTC, caibinqing commented on custom_components/xiaomi_miot/__init__.py
> +    )
```suggestion
    await hass.config_entries.async_forward_entry_setups(config_entry, SUPPORTED_DOMAINS)
```

2024-06-27 13:05 UTC, caibinqing commented on custom_components/xiaomi_miot/__init__.py
> +    )
https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups

> `hass.config_entries.async_forward_entry_setups` must always be awaited

2024-06-27 13:25 UTC, Necroneco approved these changes

2024-07-07 08:30 UTC, al-one approved these changes

2024-07-07 08:31 UTC, merged